"use client";
import {useEffect,useState} from "react"; import {ArrowDown,ArrowUpRight,Instagram,MapPin,Menu as MenuIcon,X} from "lucide-react"; import {Gallery} from "../components/Gallery"; import {MenuSection} from "../components/MenuSection"; import {MenuPhotos} from "../components/MenuPhotos"; import {SiteFooter} from "../components/SiteFooter"; import {DEFAULT_DATA,type SiteData} from "../lib/data";
export default function Home(){const[data,setData]=useState<SiteData>(DEFAULT_DATA);const[navOpen,setNavOpen]=useState(false);useEffect(()=>{const raw=localStorage.getItem("ato-site-data");if(raw)setData(JSON.parse(raw))},[]);return <main>
<header className="nav"><a className="brand" href="#">ATO<span>Ramen</span></a><nav className={navOpen?"navlinks open":"navlinks"}><a href="#story" onClick={()=>setNavOpen(false)}>O nas</a><a href="#menu" onClick={()=>setNavOpen(false)}>Menu</a><a href="#gallery" onClick={()=>setNavOpen(false)}>Galeria</a><a href="#contact" onClick={()=>setNavOpen(false)}>Kontakt</a></nav><a className="owner-nav-link" href="/owner">Panel właściciela</a><a className="nav-cta" href="#menu">Zobacz menu <ArrowUpRight size={15}/></a><button className="mobile-toggle" onClick={()=>setNavOpen(!navOpen)} aria-label="Menu">{navOpen?<X/>:<MenuIcon/>}</button></header>
<section className="hero"><div className="hero-noise"/><div className="hero-copy"><p className="eyebrow">WROCŁAW / ODRZAŃSKA 04</p><h1>Ramen,<br/><em>który zostaje.</em></h1><p className="hero-lead">Japoński comfort food po naszemu. Głębokie buliony, odważne dodatki i energia miejsca, do którego chce się wracać.</p><div className="hero-actions"><a className="button button-light" href="#menu">Nakarm ciekawość <ArrowDown size={16}/></a><a className="text-link" href="#contact">Odrzańska 4/5 <MapPin size={15}/></a></div></div><div className="hero-image"><div className="hero-image-label">NOODLES / BROTH / VIBE</div></div><div className="hero-side">01 — 04</div></section>
<section className="marquee"><span>RAMEN • UMAMI • SPICY • CRUNCH • ATO • WROCŁAW • </span><span>RAMEN • UMAMI • SPICY • CRUNCH • ATO • WROCŁAW • </span></section>
<section id="story" className="story section"><div className="section-kicker">01 / O NAS</div><div className="story-grid"><h2>Nie udajemy<br/><em>Tokio.</em></h2><div className="story-text"><p>ATO powstało z zajawki na ramen i potrzebę zrobienia po swojemu. Bez muzealnego podejścia do japońskiej kuchni. Z szacunkiem do rzemiosła, ale z miejscem na zabawę.</p><p>W centrum Wrocławia mieszamy intensywne smaki, tekstury i rzeczy, których nie spodziewasz się w misce. Przyjdź na ramen. Zostań dla klimatu.</p><a className="arrow-link" href="#gallery">Zobacz klimat <ArrowUpRight size={16}/></a></div></div></section>
<section id="menu" className="menu-section section"><div className="section-head"><div><div className="section-kicker">02 / MENU</div><h2>Miska po <em>misce.</em></h2></div><span className="section-note">40–60 zł / osoba</span></div><MenuSection items={data.menuItems}/></section>
<section className="quote"><div className="quote-mark">“</div><p>Podobno najlepszy ramen we Wrocławiu.</p><span>— opinia gościa ATO</span></section>
<Gallery items={data.gallery}/><MenuPhotos items={data.menuPhotos}/>
<section className="reviews section"><div className="section-kicker">05 / GŁOSY</div><div className="reviews-grid"><div><h2>4,5 <span>/ 5</span></h2><p>4 227 opinii w Google</p></div><div className="review-cards">{data.reviews.map((r,i)=><article className="review" key={i}><div className="stars">★★★★★</div><p>“{r.text}”</p><span>{r.author}</span></article>)}</div></div></section>
<section id="contact" className="contact section"><div className="contact-copy"><div className="section-kicker">06 / WPADAJ</div><h2>Do zobaczenia<br/><em>przy misce.</em></h2><div className="contact-list"><p><span>ADRES</span>Odrzańska 4/5<br/>50-113 Wrocław</p><p><span>GODZINY</span>Otwarte · zamknięcie 22:00<br/><small>Godziny mogą się zmieniać. Sprawdź aktualne przed wizytą.</small></p></div><a className="button button-dark" href="https://www.google.com/maps/search/?api=1&query=Odrza%C5%84ska+4%2F5%2C+50-113+Wroc%C5%82aw" target="_blank" rel="noreferrer">Wyznacz trasę <ArrowUpRight size={16}/></a></div><div className="map-card"><div className="map-grid"/><div className="map-pin"><MapPin size={26}/><strong>ATO Ramen</strong><span>Odrzańska 4/5</span></div></div></section>
<SiteFooter/><a className="owner-access" href="/owner">owner</a></main>}